### ISSUE TITLE
Using delete_source parameter also deletes the status files

### ISSUE THREAD

**Issue by mattfoxvog** [Joacchim/Scality-Cloud-Migration-Tool#47]
When using the "delete_source" configuration parameter, the status files are also deleted when the test completes.

While the migration is running, the status files are created properly and populated.  But when the migration completes, it appears those status files are also removed, even when they are in a different file location (posix:/tmp/statusDir1) than the migration-source objects (s3:srcbucket:/)

Expected:

```
/tmp/statusDir1/cloudmig.s3.amazonaws.com.to.s3.amazonaws.com/
mlz1%3a%2f  
mlz1%3a%2f.json
```

Actual: 

```
/tmp/statusDir1/
```

---

---

config.json

```
{
    "source": {
        "backend": "s3",
        "aws_region": "us-east-1",
        "host": "s3.amazonaws.com",
        "access_key": "mykey",
        "secret_key": "mysecret"
    },
    "destination": {
        "backend": "s3",
        "aws_region": "us-east-1",
        "host": "s3.amazonaws.com",
        "access_key": "mykey",
        "secret_key": "mysecret"
    },
    "status": {
        "backend": "posix",
        "base_path": "/tmp/statusDir1"
    },
    "cloudmig": {
        "buckets": {"srcbucket:/": "dstbucket:/"},
        "delete-source": true,
        "worker-threads": 10,
        "create-directories": true
    }
}
```

**Comment by Joacchim** [comment]
This behavior is actually expected, as I consider that once a migration succeeded, the default behavior should be not to leave any generated artifact behind.
